const KEY="arabic8-lesson1-progress-v4";
const today=()=>{const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")};
const defaults=()=>({version:4,diagnostic:null,topicScores:{},topicRecent:{},completedTopics:[],examAttempts:[],mistakes:[],review:{},xp:0,streak:{current:0,best:0,lastActive:null},daily:{date:today(),xp:0,goal:20,completed:false},achievements:[]});
function migrate(raw){const p={...defaults(),...(raw||{})};p.version=4;p.topicScores=p.topicScores&&typeof p.topicScores==="object"?p.topicScores:{};p.topicRecent=p.topicRecent&&typeof p.topicRecent==="object"?p.topicRecent:{};p.completedTopics=Array.isArray(p.completedTopics)?p.completedTopics:[];p.examAttempts=Array.isArray(p.examAttempts)?p.examAttempts:[];p.mistakes=Array.isArray(p.mistakes)?p.mistakes:[];p.review=p.review&&typeof p.review==="object"?p.review:{};p.achievements=Array.isArray(p.achievements)?p.achievements:[];Object.keys(p.topicRecent).forEach(k=>{p.topicRecent[k]=Array.isArray(p.topicRecent[k])?p.topicRecent[k].map(v=>v?1:0).slice(-10):[]});p.xp=Number(p.xp)||0;p.streak={current:0,best:0,lastActive:null,...(p.streak||{})};p.daily={date:today(),xp:0,goal:20,completed:false,...(p.daily||{})};if(p.daily.date!==today())p.daily={date:today(),xp:0,goal:20,completed:false};return p}
export function loadProgress(){try{const raw=localStorage.getItem(KEY);if(raw)return migrate(JSON.parse(raw));const old=localStorage.getItem("arabic8-lesson1-progress-v3");if(old){const p=migrate(JSON.parse(old));localStorage.setItem(KEY,JSON.stringify(p));return p}return defaults()}catch{return defaults()}}
export function saveProgress(p){try{localStorage.setItem(KEY,JSON.stringify(migrate(p)));return true}catch{return false}}
export function resetProgress(){try{localStorage.removeItem(KEY);localStorage.removeItem("arabic8-lesson1-progress-v3")}catch{}return defaults()}
export function recordAnswer(p,a){p.topicRecent[a.topic]??=[];p.topicRecent[a.topic].push(a.correct?1:0);p.topicRecent[a.topic]=p.topicRecent[a.topic].slice(-10);const old=p.topicScores[a.topic]||{correct:0,total:0};old.correct+=a.correct?1:0;old.total++;old.percent=Math.round(old.correct/old.total*100);p.topicScores[a.topic]=old;const r=p.review[a.id]||{interval:1,ease:2.5,due:new Date().toISOString(),streak:0};if(a.correct){r.streak++;r.interval=Math.min(30,Math.max(1,Math.round(r.interval*r.ease)));r.due=new Date(Date.now()+r.interval*86400000).toISOString();r.ease=Math.min(3.1,r.ease+.08);p.mistakes=p.mistakes.filter(id=>id!==a.id)}else{r.streak=0;r.interval=1;r.ease=Math.max(1.7,r.ease-.2);r.due=new Date(Date.now()+86400000).toISOString();if(!p.mistakes.includes(a.id))p.mistakes.push(a.id)}p.review[a.id]=r}
export function recordTopicCompletion(p,id){if(!p.completedTopics.includes(id))p.completedTopics.push(id)}
export function completeDailyGoal(p,n){const d=today();if(p.daily.date!==d)p.daily={date:d,xp:0,goal:20,completed:false};p.daily.xp+=n;if(!p.daily.completed&&p.daily.xp>=p.daily.goal){p.daily.completed=true;const last=p.streak.lastActive;if(!last)p.streak.current=1;else{const diff=Math.round((new Date(d+"T00:00:00")-new Date(last+"T00:00:00"))/86400000);p.streak.current=diff===1?p.streak.current+1:diff===0?p.streak.current:1}p.streak.best=Math.max(p.streak.best,p.streak.current);p.streak.lastActive=d}}
export function markAchievement(p,id){if(!p.achievements.includes(id))p.achievements.push(id)}