import{test,expect}from"@playwright/test";
const routes=["#home","#learn","#practice","#exam","#progress","#mistakes"];
test("responsive smoke at 320/360/390 and landscape",async({page})=>{for(const width of[320,360,390]){await page.setViewportSize({width,height:800});await page.goto("/#home");await expect(page.locator("#app")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.goto("/#practice");await expect(page.locator(".question-card,.hero")).toBeVisible()}await page.setViewportSize({width:800,height:390});await page.goto("/#learn");expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)});
test("accessibility basics and keyboard focus",async({page})=>{await page.setViewportSize({width:390,height:800});await page.goto("/#home");await expect(page.locator(".skip-link")).toBeAttached();await page.keyboard.press("Tab");await expect(page.locator(":focus")).toBeVisible();const bad=await page.locator("button").evaluateAll(btns=>btns.filter(b=>!(b.innerText||b.getAttribute("aria-label")||b.getAttribute("title"))).length);expect(bad).toBe(0);expect(await page.locator("input,select,textarea").evaluateAll(es=>es.filter(e=>!e.labels?.length&&!e.getAttribute("aria-label")&&!e.getAttribute("aria-labelledby")).length)).toBe(0);await expect(page.locator("#toast")).toHaveAttribute("role","status")});
test("storage corruption corpus always recovers",async({page})=>{const bad=[null,{},[],"banana",-999999999,NaN,Infinity,-Infinity,{xp:"💀"},{daily:[]},{streak:{current:"🔥",best:-1,lastActive:"yesterday"}},{topicScores:{x:{correct:999,total:1}},review:{x:{interval:Infinity,ease:"no",due:"banana",streak:-9,wrongCount:999}}},{examAttempts:[null,{},[],{correct:99,total:-2}],completedTopics:["x","x",9],mistakes:["x",9],achievements:["a","a",false]}];for(const value of bad){await page.goto("/#progress");await page.evaluate(v=>localStorage.setItem("arabic8-lesson1-progress-v4",JSON.stringify(v)),value);await page.reload();await expect(page.locator(".dashboard-grid")).toBeVisible();const p=await page.evaluate(()=>JSON.parse(localStorage.getItem("arabic8-lesson1-progress-v4")));expect(p.version).toBe(4);expect(Number.isFinite(p.xp)).toBeTruthy();expect(Array.isArray(p.completedTopics)).toBeTruthy();expect(Array.isArray(p.mistakes)).toBeTruthy();expect(typeof p.review).toBe("object")}};
test("state transitions survive reset and reload",async({page})=>{await page.goto("/#practice");await page.getByRole("button",{name:"شروع تمرین"}).click();await expect(page.locator(".question-card")).toBeVisible();await page.locator(".option").first().click();await page.getByRole("button",{name:"سؤال بعدی"}).click();await page.evaluate(()=>{localStorage.setItem("arabic8-lesson1-progress-v4",JSON.stringify({xp:999999,streak:{current:999,best:999},review:{bad:{due:"banana",interval:Infinity}},mistakes:["bad"],completedTopics:["x"]}))});await page.reload();await page.goto("/#progress");await expect(page.locator(".dashboard-grid")).toBeVisible();await page.evaluate(()=>localStorage.removeItem("arabic8-lesson1-progress-v4"));await page.reload();await expect(page.locator(".hero")).toBeVisible();});
test("exam state machine is navigable and bounded",async({page})=>{await page.goto("/#exam");await page.getByRole("button",{name:"شروع آزمون"}).click();await expect(page.locator(".exam-nav button")).toHaveCount(20);for(const i of[19,0,5,10]){await page.locator('.exam-nav button[data-i="'+i+'"]').click();await expect(page.locator(".question-card")).toBeVisible()}await page.reload();await expect(page.locator(".hero,.question-card")).toBeVisible()});
test("practice summary and mistake review",async({page})=>{await page.goto("/#learn");await page.locator('.path-card [data-id="colors"][data-a="topic"]').click();await page.getByRole("button",{name:"تمرین این موضوع"}).click();await page.locator(".option").first().click();await page.goto("/#mistakes");await expect(page.locator(".review-item").first()).toBeVisible();await page.locator('.review-item [data-a="quiz"]').click();await expect(page.locator(".question-card")).toBeVisible()});
test("offline/PWA hooks are present",async({page})=>{await page.goto("/#home");await expect(page.locator("#networkStatus")).toBeAttached();await page.evaluate(()=>window.dispatchEvent(new Event("offline")));await expect(page.locator("#networkStatus")).toHaveText(/آفلاین/);await page.evaluate(()=>window.dispatchEvent(new Event("online")));await expect(page.locator("#networkStatus")).toHaveText(/آنلاین/)});
