import{test,expect}from"@playwright/test";
test("mobile learning path and quiz",async({page})=>{await page.goto("/");await expect(page.locator("main#app")).toBeVisible();await expect(page.locator(".mobile-nav")).toBeVisible();await expect(page.locator(".sidebar nav a")).toHaveCount(5);await expect(page.locator(".sidebar nav a").first()).toHaveAttribute("href","#home");await expect(page.locator(".path-card").first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.locator('.mobile-nav [data-route="learn"]').click();await expect(page).toHaveURL(/#learn$/);await page.locator('.path-card [data-id="colors"][data-a="topic"]').click();await expect(page.locator(".micro-lesson")).toBeVisible();await page.getByRole("button",{name:"تمرین این موضوع"}).click();await expect(page.locator(".question-card")).toBeVisible();const answerButton=page.locator(".option").first();if(await answerButton.count()){await answerButton.click()}else if(await page.locator("[data-a=word]").count()){await page.locator("[data-a=word]").first().click();await page.locator("[data-a=submit-word]").click()}else if(await page.locator("[data-a=order]").count()){while(await page.locator("[data-a=order]").count())await page.locator("[data-a=order]").first().click();await page.locator("[data-a=submit-order]").click()}await expect(page.locator("#feedback")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)});
test("progress dashboard exists",async({page})=>{await page.goto("/#progress");await expect(page.locator(".dashboard-grid")).toBeVisible();await expect(page.locator(".achievement-grid")).toBeVisible();expect(await page.locator(".ui-icon").count()).toBeGreaterThan(0)});
test("question types render",async({page})=>{await page.goto("/#practice");await page.getByRole("button",{name:"شروع تمرین"}).click();await expect(page.locator(".question-card")).toBeVisible();await expect(page.locator(".question-card h2")).toBeVisible()});
test("malformed saved progress recovers",async({page})=>{await page.goto("/");await page.evaluate(()=>localStorage.setItem("arabic8-lesson1-progress-v4","{broken"));await page.reload();await expect(page.locator("main#app")).toBeVisible();await page.goto("/#progress");await expect(page.locator(".dashboard-grid")).toBeVisible()});
test("visual practice renders safely",async({page})=>{await page.goto("/#learn");await page.locator('.path-card [data-id="visual-practice"][data-a="topic"]').click();await page.getByRole("button",{name:"تمرین این موضوع"}).click();await expect(page.locator(".quiz-visual img")).toBeVisible();await expect(page.locator(".quiz-visual img")).toHaveAttribute("alt",/./);});

test("practice session summary appears",async({page})=>{await page.goto("/#learn");await page.locator('.path-card [data-id="colors"][data-a="topic"]').click();await page.getByRole("button",{name:"تمرین این موضوع"}).click();for(let i=0;i<6;i++){await page.locator(".option").first().click();await page.getByRole("button",{name:i===5?"دیدن نتیجه":"سؤال بعدی"}).click()}await expect(page.locator(".session-summary")).toBeVisible()});
test("exam controls render",async({page})=>{await page.goto("/#exam");await page.getByRole("button",{name:"شروع آزمون"}).click();await expect(page.locator(".exam-timer")).toBeVisible();await expect(page.locator(".exam-nav button")).toHaveCount(20);await page.locator('.exam-nav button[data-i="5"]').click();await expect(page.locator(".question-card")).toBeVisible()});

test("mistake review is actionable",async({page})=>{await page.goto("/#learn");await page.locator('.path-card [data-id="colors"][data-a="topic"]').click();await page.getByRole("button",{name:"تمرین این موضوع"}).click();await page.locator(".option").first().click();await page.goto("/#mistakes");await expect(page.locator(".review-item").first()).toBeVisible();await expect(page.locator(".review-item").first().locator("small")).toContainText("این سؤال قبلاً اشتباه شده است")});
